### PR TITLE
Big Refactor

### LINKED ISSUE #5: CLN - Moves ipynb from src to notebooks folder
I suggest move notebooks from `src` to another folder (`notebook` maybe?) in order to modularize the code and make it easier to maintain and extend it. I see a notebook like an application which uses the source code (`src`).  What do you think @KikeM ?

### PR DESCRIPTION
**Pull request by asdf8601**
TODO : 

- [x] Add issues related with this PR.
- [x] Comments
- [x] Check typos and flake8

Closes #5 #6 #8 #13 #14 #20

### CODE REVIEW

**Review by emvalbuena — APPROVED** [review]
Everything looks fine to me. 

Great work, thank you!

**Comment by emvalbuena** [comment]
**Comments**

- The `_ss` suffix indicates it is a `pd.Series`.

- I could run programmatically this https://pypi.org/project/pyspellchecker/ to look for typos ;) 

- [x] The idea is to update the `nb2py` scripts when a new notebook is included? If this is the case I am in favor. 

- [x] Do we include `versioneer` all ready?

@mmngreco

**Comment by asdf8601** [comment]
> The idea is to update the nb2py scripts when a new notebook is included? If this is the case I am in favor.

Yes, That could be the future behavior, for now I will say that we should run each script manually. We can start to think on how automatize this process by using it (related https://github.com/KikeM/degiro-wrapper/issues/25)

> I could run programmatically this https://pypi.org/project/pyspellchecker/ to look for typos ;)

Ohh nice! I like it!

> Do we include versioneer all ready?

Yes, We can add it after this PR. What do you think?

**Comment by emvalbuena** [comment]
By the way, we have already added the issues related to this PR, right?

Otherwise I don't know to which issues you are referring.

**Comment by asdf8601** [comment]
> By the way, we have already added the issues related to this PR, right?

Not yet... Otherwise we will see them here, thought. XD

**Comment by asdf8601** [comment]
I will try to reference all issues ASAP. I let you know when I have it done.

**Comment by asdf8601** [comment]
It's ready to merge!

**Review by emvalbuena — APPROVED** [review]
Push to prod ;)

**Pull request merged**
